
import json
import os
from urlparse import urlparse
import zipfile 

import click

import adapters
from filters import BasicFilterer
import utils
import subprocess
 
@click.command()
@click.argument('file', type=click.Path(exists=True), required=True)
def vectorTiling(file):
    """ Function that creates vector tiles
    INPUT: geojson file generated by process.py 
    OUTPUT: mbtiles file containing vector tiles 
    """
    # Variables to change in production 
    path = '/Users/athissen/Documents/'

    min_zoom = 0 
    max_zoom = 14   
    paths_string = ''

    with open(file, 'rb') as f: 
        geojson = json.load(f)
    features = geojson['features']
    for item in features: 
        paths_string += path + item['properties']['path'] + ' '

    command = 'tippecanoe -f -o ' + 'result.mbtiles ' + paths_string + ' -z {} -Z {}'.format(max_zoom, min_zoom)
    subprocess.call(command,shell=True)


if __name__ == '__main__':

    vectorTiling()
    